/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testRegex: '(/tests/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$',
  transform: {'^.+\\.(ts|tsx)$': 'ts-jest'},
  transformIgnorePatterns: ['<rootDir>/node_modules/(?!@foo)'],
  moduleNameMapper: {
    '^.+\\.(css|less|scss|sass|png|svg)$': 'babel-jest',
    '@/(.*)': '<rootDir>/src/$1',
    // '@api': '<rootDir>/src/api',
    // '@api/repositories': '<rootDir>/src/api/repositories',
    // '@api/types': '<rootDir>/src/api/types',
    // '@api/sockets/chat': '<rootDir>/src/api/sockets/chat.ts',
    // '@app/actions': '<rootDir>/src/app/actions',
    // '@app/functions': '<rootDir>/src/app/functions',
    // '@app/utils': '<rootDir>/src/app/utils',
    // '@app/pages': '<rootDir>/src/app/pages',
    // '@app/components': '<rootDir>/src/app/components',
    // '@app/types': '<rootDir>/src/app/types',
    // '@app/resources': '<rootDir>/src/app/resources',
    // '@app/modules': '<rootDir>/src/app/modules',
    // '@app/constants': '<rootDir>/src/app/constants',
    // '@app/img': '<rootDir>/src/app/static/img',
    // '@app/styles': '<rootDir>/src/app/styles',
    // '@app/styles/varibales': '<rootDir>/src/app/styles/varibales.sass',
    // '@app/styles/mixins': '<rootDir>/src/app/styles/mixins.sass',
    // '@app/styles/global': '<rootDir>/src/app/styles/global.sass',
    // '@core/types': '<rootDir>/src/core/types.ts',
    // '@core/tags': '<rootDir>/src/core/vdom/tags/tags.ts',
    // '@core/http': '<rootDir>/src/core/http/http.ts',
    // '@core/utils': '<rootDir>/src/core/utils',
    // '@core/component': '<rootDir>/src/core/component/component.ts',
    // '@core/router': '<rootDir>/src/core/router/router.ts',
  },
};
